In [11]:
import torch
import numpy as np 

In [5]:
vector = torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [8]:
matrix = torch.tensor([[1,2,3],[4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
np_array = np.array([[1,2,3],[3,4,5],[3,3,3]])
np_array
matrix = torch.from_numpy(np_array)
matrix

torch_array = torch.tensor(np_array)

In [18]:
torch_array.shape

torch.Size([3, 3])

In [19]:
np_array.dtype

dtype('int32')

In [20]:
np_array.ndim

2

In [33]:
matrix = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.int64)
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [34]:
tensor_unsqueeze = matrix.unsqueeze(-1)
tensor_unsqueeze

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])

In [23]:
shape = (2,3)
rand_tensor = torch.rand(shape)
rand_tensor

tensor([[0.4508, 0.8623, 0.3583],
        [0.6233, 0.7324, 0.9289]])

In [44]:
tensor1 = torch.tensor([[1,2],[3,4]])
tensor2 = torch.tensor([[5,6],[7,8]])
result = torch.stack((tensor1,tensor2),dim=1)
result


tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])

In [60]:
matrix = torch.tensor([[1,2,3],[4,5,6]])
res = torch.sum(matrix,axis=0)
res

tensor([5, 7, 9])

In [62]:
torch.cuda.is_available()
matrix.device

device(type='cpu')

In [63]:
matrix = matrix.to('cuda')
matrix.device

device(type='cuda', index=0)

In [64]:
!nvidia-smi

Sat Jun  1 09:18:38 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.85                 Driver Version: 555.85         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   43C    P0             17W /  115W |       0MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [89]:
y = torch.tensor([5],dtype=torch.float32)
x1 = torch.tensor([3],dtype=torch.float32)
x2 = torch.tensor([1],dtype=torch.float32)

w1 = torch.tensor([0.5],requires_grad=True, dtype=torch.float32)
w2 = torch.tensor([0.5],requires_grad=True, dtype=torch.float32)

x1w1 = torch.mul(x1,w1)
x2w2 = torch.mul(x2,w2)

result = x1w1+x2w2
result

loss = torch.nn.functional.mse_loss(result,y)
loss.backward()

w1.grad



tensor([-18.])